version: "3.8"

services:

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db

  app:
    container_name: app
    build: # TODO migrate this to CI rather than building here
      context: .
      dockerfile: Dockerfile
    # command: bash -c "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    image: iou_app
    env_file:
      - .env
    volumes: # is this needed?
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

  bot:
    container_name: bot
    image: iou_bot
    # command: bash -c "python -m app.main"
    depends_on:
      - app
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}