services:
  app:
    container_name: iou_app
    image: ghcr.io/skycarl/iou_app:latest
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: bash -c "uvicorn iou_app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  bot:
    container_name: iou_bot
    image: ghcr.io/skycarl/iou_bot:latest
    command: bash -c "python -m iou_bot.main"
    depends_on:
      - app
    restart: always
    environment:
      - LOG_LEVEL=DEBUG
    env_file:
      - .env
    volumes:
      - ${HOST_PATH}:/app/config/
