version: "3.8"

services:
  app:
    container_name: iou_app
    image: ghcr.io/skycarl/iou_app:latest
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env

  bot:
    container_name: iou_bot
    image: ghcr.io/skycarl/iou_bot:latest
    command: bash -c "python -m app.main"
    depends_on:
      - app
    restart: always
    env_file:
      - .env
