"""Add entries and remove boilerplate

Revision ID: 15647270e3d8
Revises: baa9097006be
Create Date: 2023-11-29 05:51:28.001193

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '15647270e3d8'
down_revision = 'baa9097006be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('recipient', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_id'), 'entries', ['id'], unique=False)
    op.drop_index('ix_sneaker_brand_name', table_name='sneaker')
    op.drop_index('ix_sneaker_color', table_name='sneaker')
    op.drop_index('ix_sneaker_description', table_name='sneaker')
    op.drop_index('ix_sneaker_free_delivery', table_name='sneaker')
    op.drop_index('ix_sneaker_name', table_name='sneaker')
    op.drop_index('ix_sneaker_size', table_name='sneaker')
    op.drop_table('sneaker')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sneaker',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('free_delivery', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sneaker_pkey')
    )
    op.create_index('ix_sneaker_size', 'sneaker', ['size'], unique=False)
    op.create_index('ix_sneaker_name', 'sneaker', ['name'], unique=False)
    op.create_index('ix_sneaker_free_delivery', 'sneaker', ['free_delivery'], unique=False)
    op.create_index('ix_sneaker_description', 'sneaker', ['description'], unique=False)
    op.create_index('ix_sneaker_color', 'sneaker', ['color'], unique=False)
    op.create_index('ix_sneaker_brand_name', 'sneaker', ['brand_name'], unique=False)
    op.drop_index(op.f('ix_entries_id'), table_name='entries')
    op.drop_table('entries')
    # ### end Alembic commands ###
