"""Update conversation ID column

Revision ID: dd8f0ceb0cc1
Revises: 15647270e3d8
Create Date: 2024-06-15 13:05:27.901528

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'dd8f0ceb0cc1'
down_revision = '15647270e3d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entries_id', table_name='entries')
    op.drop_table('entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('datetime', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'),
              autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recipient', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='entries_pkey')
    )
    op.create_index('ix_entries_id', 'entries', ['id'], unique=False)
    # ### end Alembic commands ###
