# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  # Build and test the project
  build-test-repo:
    name: Build and test project

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    - name: Install project
      run: poetry install --no-interaction

    - name: Lint with ruff
      uses: chartboost/ruff-action@v1
      with:
        args: --no-fix --line-length=120

    - name: Test with pytest
      run: |
        poetry run pytest
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/dummy_db
        X_TOKEN: 12345678910

    - name: Zip artifact for deployment
      run: zip release.zip ./* -r

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v3
      with:
        name: iou-app
        path: |
          release.zip
          !venv/
